/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kelompok5.kelompok5app.view;

/**
 *
 * @author LENOVO
 */
public class DashboardPPIC extends javax.swing.JFrame {

    /**
     * Creates new form DashboardPPIC
     */
    public DashboardPPIC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        txtppic = new javax.swing.JLabel();
        BtnPanel = new javax.swing.JPanel();
        BtnCreateLaporan = new javax.swing.JButton();
        BtnListLaporan = new javax.swing.JButton();
        BottomPanel = new javax.swing.JPanel();
        ScrollTabelProduk = new javax.swing.JScrollPane();
        TabelProduk = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(153, 153, 153));
        bg.setLayout(new java.awt.BorderLayout());

        Header.setMinimumSize(new java.awt.Dimension(800, 75));
        Header.setOpaque(false);
        Header.setPreferredSize(new java.awt.Dimension(800, 75));
        Header.setLayout(new java.awt.BorderLayout());

        txtppic.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtppic.setText("PPIC");
        txtppic.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        Header.add(txtppic, java.awt.BorderLayout.LINE_START);

        BtnPanel.setMinimumSize(new java.awt.Dimension(315, 75));
        BtnPanel.setOpaque(false);
        BtnPanel.setPreferredSize(new java.awt.Dimension(315, 75));
        BtnPanel.setLayout(new java.awt.GridBagLayout());

        BtnCreateLaporan.setBackground(new java.awt.Color(0, 0, 0));
        BtnCreateLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCreateLaporan.setForeground(new java.awt.Color(255, 255, 255));
        BtnCreateLaporan.setText("Buat Laporan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        BtnPanel.add(BtnCreateLaporan, gridBagConstraints);

        BtnListLaporan.setBackground(new java.awt.Color(0, 0, 0));
        BtnListLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnListLaporan.setForeground(new java.awt.Color(255, 255, 255));
        BtnListLaporan.setText("List Laporan");
        BtnListLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListLaporanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        BtnPanel.add(BtnListLaporan, gridBagConstraints);

        Header.add(BtnPanel, java.awt.BorderLayout.EAST);

        bg.add(Header, java.awt.BorderLayout.PAGE_START);

        BottomPanel.setOpaque(false);
        BottomPanel.setLayout(new java.awt.BorderLayout());

        TabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Produk", "Nama Produk", "Material Produk", "Stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabelProduk.setShowGrid(true);
        ScrollTabelProduk.setViewportView(TabelProduk);

        BottomPanel.add(ScrollTabelProduk, java.awt.BorderLayout.CENTER);

        bg.add(BottomPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnListLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListLaporanActionPerformed
            // TODO add your handling code here:
            new DashboardLaporanProduk().setVisible(true);
    }//GEN-LAST:event_BtnListLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardPPIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardPPIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardPPIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardPPIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardPPIC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton BtnCreateLaporan;
    private javax.swing.JButton BtnListLaporan;
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JPanel Header;
    private javax.swing.JScrollPane ScrollTabelProduk;
    private javax.swing.JTable TabelProduk;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel txtppic;
    // End of variables declaration//GEN-END:variables
}
