/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kelompok5.kelompok5app.view;

/**
 *
 * @author LENOVO
 */
public class DashboardLaporanProduk extends javax.swing.JFrame {

    /**
     * Creates new form ListLaporanProduk
     */
    public DashboardLaporanProduk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        textHeader = new javax.swing.JLabel();
        PanelKembali = new javax.swing.JPanel();
        BtnKembaliLaporan = new javax.swing.JButton();
        BottomPanel = new javax.swing.JPanel();
        ScrollLaporanProduk = new javax.swing.JScrollPane();
        TabelListLaporanProduk = new javax.swing.JTable();
        NavbarLaporanProduk = new javax.swing.JPanel();
        btnNavbarDDLaporan = new javax.swing.JPanel();
        BtnLogout = new javax.swing.JButton();
        BtnBuatLaporan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(153, 153, 153));
        bg.setLayout(new java.awt.BorderLayout());

        Header.setOpaque(false);
        Header.setPreferredSize(new java.awt.Dimension(800, 75));
        Header.setLayout(new java.awt.BorderLayout());

        textHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textHeader.setText("Dashboard Laporan Produk");
        textHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        Header.add(textHeader, java.awt.BorderLayout.CENTER);

        PanelKembali.setOpaque(false);
        PanelKembali.setPreferredSize(new java.awt.Dimension(150, 75));
        PanelKembali.setLayout(new java.awt.GridBagLayout());

        BtnKembaliLaporan.setBackground(new java.awt.Color(0, 0, 0));
        BtnKembaliLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnKembaliLaporan.setForeground(new java.awt.Color(255, 255, 255));
        BtnKembaliLaporan.setText("Kembali");
        BtnKembaliLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKembaliLaporanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        PanelKembali.add(BtnKembaliLaporan, gridBagConstraints);

        Header.add(PanelKembali, java.awt.BorderLayout.EAST);

        bg.add(Header, java.awt.BorderLayout.PAGE_START);

        BottomPanel.setOpaque(false);
        BottomPanel.setLayout(new java.awt.BorderLayout());

        TabelListLaporanProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Produk", "Material_Produk", "Maks Stok", "Stok Tersedia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabelListLaporanProduk.setShowGrid(true);
        ScrollLaporanProduk.setViewportView(TabelListLaporanProduk);

        BottomPanel.add(ScrollLaporanProduk, java.awt.BorderLayout.CENTER);

        NavbarLaporanProduk.setMinimumSize(new java.awt.Dimension(800, 75));
        NavbarLaporanProduk.setOpaque(false);
        NavbarLaporanProduk.setPreferredSize(new java.awt.Dimension(800, 75));
        NavbarLaporanProduk.setLayout(new java.awt.BorderLayout());

        btnNavbarDDLaporan.setMinimumSize(new java.awt.Dimension(200, 75));
        btnNavbarDDLaporan.setOpaque(false);
        btnNavbarDDLaporan.setPreferredSize(new java.awt.Dimension(225, 75));
        btnNavbarDDLaporan.setLayout(new java.awt.GridBagLayout());

        BtnLogout.setBackground(new java.awt.Color(0, 0, 0));
        BtnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnLogout.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogout.setText("Keluar");
        BtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        btnNavbarDDLaporan.add(BtnLogout, gridBagConstraints);

        BtnBuatLaporan.setBackground(new java.awt.Color(0, 0, 0));
        BtnBuatLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBuatLaporan.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuatLaporan.setText("Tambah Stok");
        BtnBuatLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuatLaporanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        btnNavbarDDLaporan.add(BtnBuatLaporan, gridBagConstraints);

        NavbarLaporanProduk.add(btnNavbarDDLaporan, java.awt.BorderLayout.EAST);

        BottomPanel.add(NavbarLaporanProduk, java.awt.BorderLayout.PAGE_END);

        bg.add(BottomPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKembaliLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKembaliLaporanActionPerformed
        // TODO add your handling code here:
        new DashboardPPIC().setVisible(true);

        // Menutup frame DetailLaporanBarang
        dispose();
    }//GEN-LAST:event_BtnKembaliLaporanActionPerformed

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);

        // Menutup frame DetailLaporanBarang
        dispose();

    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void BtnBuatLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuatLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuatLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardLaporanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardLaporanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardLaporanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardLaporanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardLaporanProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton BtnBuatLaporan;
    private javax.swing.JButton BtnKembaliLaporan;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel NavbarLaporanProduk;
    private javax.swing.JPanel PanelKembali;
    private javax.swing.JScrollPane ScrollLaporanProduk;
    private javax.swing.JTable TabelListLaporanProduk;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnNavbarDDLaporan;
    private javax.swing.JLabel textHeader;
    // End of variables declaration//GEN-END:variables
}
