/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kelompok5.kelompok5app.view;

import com.kelompok5.kelompok5app.controller.BarangController;

/**
 *
 * @author LENOVO
 */
public class DashboardDepartemenGudang extends javax.swing.JFrame {

    private BarangController barangController;

    /**
     * Creates new form DashboardDepartemenGudang
     */
    public DashboardDepartemenGudang() {
        initComponents();
        barangController = new BarangController();
        barangController.tampilkanSemuaBarang(TabelBarang); // Ini akan isi datanya

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        txtDg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtnDashboardLaporan = new javax.swing.JButton();
        BtnListLaporan = new javax.swing.JButton();
        BottomPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelBarang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(153, 153, 153));
        bg.setLayout(new java.awt.BorderLayout());

        Header.setMinimumSize(new java.awt.Dimension(800, 75));
        Header.setOpaque(false);
        Header.setPreferredSize(new java.awt.Dimension(800, 75));
        Header.setLayout(new java.awt.BorderLayout());

        txtDg.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtDg.setText("Departemen Gudang");
        txtDg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        Header.add(txtDg, java.awt.BorderLayout.CENTER);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(315, 75));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        BtnDashboardLaporan.setBackground(new java.awt.Color(0, 0, 0));
        BtnDashboardLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnDashboardLaporan.setForeground(new java.awt.Color(255, 255, 255));
        BtnDashboardLaporan.setText("Dashboard Laporan");
        BtnDashboardLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDashboardLaporanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(BtnDashboardLaporan, gridBagConstraints);

        BtnListLaporan.setBackground(new java.awt.Color(0, 0, 0));
        BtnListLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnListLaporan.setForeground(new java.awt.Color(255, 255, 255));
        BtnListLaporan.setText("List Laporan");
        BtnListLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListLaporanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel1.add(BtnListLaporan, gridBagConstraints);

        Header.add(jPanel1, java.awt.BorderLayout.EAST);

        bg.add(Header, java.awt.BorderLayout.PAGE_START);

        BottomPanel.setOpaque(false);
        BottomPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(800, 425));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 425));

        TabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Kategori", "Min Stok", "Maks Stok", "Stok", "Order", "Vendor",
                "Tanggal Diperbarui"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabelBarang.setShowGrid(true);
        jScrollPane1.setViewportView(TabelBarang);

        BottomPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        bg.add(BottomPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDashboardLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDashboardLaporanActionPerformed
        // TODO add your handling code here:
        new DashboardLaporan().setVisible(true);

        // Menutup frame DashboardDepartemenGudang
        dispose();
    }//GEN-LAST:event_BtnDashboardLaporanActionPerformed

    private void BtnListLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListLaporanActionPerformed
        // TODO add your handling code here:
        new Laporan().setVisible(true);

        // Menutup frame DashboardDepartemenGudang
        dispose();
    }//GEN-LAST:event_BtnListLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardDepartemenGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardDepartemenGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardDepartemenGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardDepartemenGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardDepartemenGudang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton BtnDashboardLaporan;
    private javax.swing.JButton BtnListLaporan;
    private javax.swing.JPanel Header;
    private javax.swing.JTable TabelBarang;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtDg;
    // End of variables declaration//GEN-END:variables
}
