/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kelompok5.kelompok5app.view;

/**
 *
 * @author LENOVO
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        txtHeader = new javax.swing.JLabel();
        fieldPanel = new javax.swing.JPanel();
        txtFieldbarang = new javax.swing.JTextField();
        txtFieldProduk = new javax.swing.JTextField();
        txtProduk = new javax.swing.JLabel();
        txtBarang = new javax.swing.JLabel();
        BottomPanel = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        NavbarContainer = new javax.swing.JPanel();
        BtnPesan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(153, 153, 153));
        bg.setLayout(new java.awt.BorderLayout());

        Header.setOpaque(false);
        Header.setPreferredSize(new java.awt.Dimension(800, 75));
        Header.setLayout(new java.awt.BorderLayout());

        txtHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtHeader.setText("Order");
        txtHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        Header.add(txtHeader, java.awt.BorderLayout.CENTER);

        fieldPanel.setOpaque(false);
        fieldPanel.setPreferredSize(new java.awt.Dimension(400, 75));
        fieldPanel.setLayout(new java.awt.GridBagLayout());

        txtFieldbarang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFieldbarang.setMinimumSize(new java.awt.Dimension(125, 30));
        txtFieldbarang.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtFieldbarang, gridBagConstraints);

        txtFieldProduk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFieldProduk.setMinimumSize(new java.awt.Dimension(125, 30));
        txtFieldProduk.setPreferredSize(new java.awt.Dimension(150, 30));
        txtFieldProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldProdukActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtFieldProduk, gridBagConstraints);

        txtProduk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtProduk.setText("Produk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtProduk, gridBagConstraints);

        txtBarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtBarang.setText("Barang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        fieldPanel.add(txtBarang, gridBagConstraints);

        Header.add(fieldPanel, java.awt.BorderLayout.EAST);

        bg.add(Header, java.awt.BorderLayout.PAGE_START);

        BottomPanel.setOpaque(false);
        BottomPanel.setLayout(new java.awt.BorderLayout());

        Navbar.setOpaque(false);
        Navbar.setPreferredSize(new java.awt.Dimension(800, 75));
        Navbar.setLayout(new java.awt.BorderLayout());

        NavbarContainer.setMinimumSize(new java.awt.Dimension(200, 75));
        NavbarContainer.setOpaque(false);
        NavbarContainer.setPreferredSize(new java.awt.Dimension(200, 75));
        NavbarContainer.setLayout(new java.awt.GridBagLayout());

        BtnPesan.setBackground(new java.awt.Color(0, 0, 0));
        BtnPesan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnPesan.setForeground(new java.awt.Color(255, 255, 255));
        BtnPesan.setText("Buat Pesanan");
        BtnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        NavbarContainer.add(BtnPesan, gridBagConstraints);

        Navbar.add(NavbarContainer, java.awt.BorderLayout.EAST);

        BottomPanel.add(Navbar, java.awt.BorderLayout.PAGE_END);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Barang", "Nama Produk", "Stok Barang", "Stok Produk"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        BottomPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        bg.add(BottomPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPesanActionPerformed

    private void txtFieldProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldProdukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton BtnPesan;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Navbar;
    private javax.swing.JPanel NavbarContainer;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel fieldPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtBarang;
    private javax.swing.JTextField txtFieldProduk;
    private javax.swing.JTextField txtFieldbarang;
    private javax.swing.JLabel txtHeader;
    private javax.swing.JLabel txtProduk;
    // End of variables declaration//GEN-END:variables
}
