/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kelompok5.kelompok5app.view;

/**
 *
 * @author LENOVO
 */
public class Purchasing extends javax.swing.JFrame {

    /**
     * Creates new form Purchasing
     */
    public Purchasing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        txtHeader = new javax.swing.JLabel();
        BottomPanel = new javax.swing.JPanel();
        ScrollPurchasing = new javax.swing.JScrollPane();
        TabelPurchasing = new javax.swing.JTable();
        NavbarPanel = new javax.swing.JPanel();
        NavbarContainer = new javax.swing.JPanel();
        BtnDetail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(153, 153, 153));
        bg.setLayout(new java.awt.BorderLayout());

        Header.setMinimumSize(new java.awt.Dimension(800, 75));
        Header.setOpaque(false);
        Header.setPreferredSize(new java.awt.Dimension(800, 75));
        Header.setLayout(new java.awt.BorderLayout());

        txtHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtHeader.setText("PURCHASING");
        txtHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        Header.add(txtHeader, java.awt.BorderLayout.CENTER);

        bg.add(Header, java.awt.BorderLayout.PAGE_START);

        BottomPanel.setOpaque(false);
        BottomPanel.setLayout(new java.awt.BorderLayout());

        TabelPurchasing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Laporan", "Setuju", "Tolak"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabelPurchasing.setShowGrid(true);
        ScrollPurchasing.setViewportView(TabelPurchasing);

        BottomPanel.add(ScrollPurchasing, java.awt.BorderLayout.CENTER);

        NavbarPanel.setMinimumSize(new java.awt.Dimension(800, 75));
        NavbarPanel.setOpaque(false);
        NavbarPanel.setPreferredSize(new java.awt.Dimension(800, 75));
        NavbarPanel.setLayout(new java.awt.BorderLayout());

        NavbarContainer.setMinimumSize(new java.awt.Dimension(200, 75));
        NavbarContainer.setOpaque(false);
        NavbarContainer.setPreferredSize(new java.awt.Dimension(200, 75));
        NavbarContainer.setLayout(new java.awt.GridBagLayout());

        BtnDetail.setBackground(new java.awt.Color(0, 0, 0));
        BtnDetail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnDetail.setForeground(new java.awt.Color(255, 255, 255));
        BtnDetail.setText("Lihat Detail");
        BtnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDetailActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        NavbarContainer.add(BtnDetail, gridBagConstraints);

        NavbarPanel.add(NavbarContainer, java.awt.BorderLayout.EAST);

        BottomPanel.add(NavbarPanel, java.awt.BorderLayout.PAGE_END);

        bg.add(BottomPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDetailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchasing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton BtnDetail;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel NavbarContainer;
    private javax.swing.JPanel NavbarPanel;
    private javax.swing.JScrollPane ScrollPurchasing;
    private javax.swing.JTable TabelPurchasing;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel txtHeader;
    // End of variables declaration//GEN-END:variables
}
